# This is a basic workflow to help you get started with Actions

name: Build and deploy Elm app

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and deploy Elm app
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1
          
      - name: Download API definition
        run: wget -O ./openapi.json https://github.com/MatusPilnan/vnos-2020/releases/latest/download/openapi.json
        
      - name: Cache API client
        id: cache-api
        uses: actions/cache@v2
        with:
          path: ./api
          key: ${{ runner.os }}-${{ hashFiles('./openapi.json') }}
          
      - name: Generate API client
        if: steps.cache-api.outputs.cache-hit != 'true'
        run: ./generate_api.sh

      - name: Build Elm app
        run: elm make src/Main.elm --output elm.js
        
      - name: Move files
        run: |
          mkdir ./public
          mv ./index.html ./public
          mv ./styles.css ./public
          mv ./elm.js ./public
          mv ./assets/ ./public/
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
          
          
          
          
          
          
          
          
          
          
          
          
